# Simple worker configuration (no Durable Objects)
name = "vibe-signaling-simple"
main = "src/workers/simple-worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# No Durable Objects, works on free tier

[vars]
LOG_LEVEL = "info"

[env.dev]
name = "vibe-signaling-simple-dev"
vars = { LOG_LEVEL = "debug" }

[env.production]
name = "vibe-signaling-simple-prod"
route = { pattern = "signaling-simple.yourdomain.com/*" }